version: 2.1
jobs:
  build:

    working_directory: ~/cicd-demo

    docker:
      - image: circleci/openjdk:8-jdk

    steps:

      - checkout

      - restore_cache:
          key: cicd-demo-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: cicd-demo-{{ checksum "pom.xml" }}

      - run: mvn test

      - store_test_results:
          path: target/surefire-reports

      - store_artifacts:
          path: target/cicd-demo-cf.jar
