version: 2.1
jobs:
  build:

    working_directory: ~/cicd-demo

    docker:
      - image: circleci/openjdk

    steps:

      - checkout

      - restore_cache:
          key: cicd-demo-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: cicd-demo-{{ checksum "pom.xml" }}

      - run: mvn clean install spring-boot:repackage -P cloudfoundry

      - store_test_results:
          path: target/surefire-reports
